server {
    listen 80;
    server_name localhost;

    client_max_body_size 20M;

    # 1. API Бэкенда
    location ~ ^/(auth|users|tasks|lists|steps|docs|openapi\.json) {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Основное приложение
    location /app/ {
        proxy_pass http://frontend:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        error_page 404 =200 /index.html;
    }

    # 3. Лендинг
    location / {
        add_header X-Debug-Cookies $http_cookie; 
        if ($http_cookie ~* "access_token") {
            return 302 /app/;
        }
        proxy_pass http://landing:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        error_page 404 =200 /index.html;
    }
    
}